### ISSUE TITLE
BKMC Checklist

### ISSUE THREAD

**Issue by bushramustafa** [codeforpakistan/HCAIs-Surveillance-App#125]
- [ ] Update SSI Definition
- [ ] Add Surgeon Level field in first step (auto-generate)
- [ ] Add Patient Address in the second step till the lowest level available
- [ ] Add SSI Criteria in the third step
- [ ]  Add SSI detected field with within the fourth step and

**Comment by bushramustafa** [comment]
Reference document [https://docs.google.com/document/d/1Vpf5t5kgJB2NpyzEBTZws6dgoEx7Kxed76elH9-HzGU/edit?usp=sharing](url)

**Comment by aliirz** [comment]
https://docs.google.com/document/d/1Vpf5t5kgJB2NpyzEBTZws6dgoEx7Kxed76elH9-HzGU/edit

**Comment by aliirz** [comment]
https://icd.who.int/en

**Comment by bushramustafa** [comment]
@sohail0992 SSI Detected field is missing.

**Comment by bushramustafa** [comment]
@sohail0992 please please use the same approach for Type of SSI as the SSI Criteria field

**Comment by bushramustafa** [comment]
@sohail0992 please add radio button descriptions in brackets to Wound Class field (Check document).

**Comment by bushramustafa** [comment]
@sohail0992 please show an editable text field if Others option is selected in Comorbid Condition field

**Comment by bushramustafa** [comment]
@sohail0992 please add the content in the bracket to information icon for this field: Additional Dose During Procedure (Operation more than 4 hours or major blood loss)

**Comment by bushramustafa** [comment]
@sohail0992 update Proper Skin Preparation to Proper Skin Preparation & Allowed to Dry

**Comment by sohail0992** [comment]
- [ ]  SSI Detected field is missing.
- [ ] please use the same approach for Type of SSI as the SSI Criteria field
- [ ] please add radio button descriptions in brackets to Wound Class field (Check document).
- [ ]  please show an editable text field if Others option is selected in Comorbid Condition field
- [ ] please add the content in the bracket to information icon for this field: Additional Dose During Procedure (Operation more than 4 hours or major blood loss)
- [ ] Surgical Hand Preparation and Time Spent on Procedure fields are missing in the step 8
- [ ] update Proper Skin Preparation to Proper Skin Preparation & Allowed to Dry. Also please re-check step 8, a number of fields are missing.

**Comment by sohail0992** [comment]
Working: Step 7 Antimicrobial Prophylaxis Administered (Radio Buttons - If yes, show the Fields from 11 to 14)
Fixed (Download APK) Step 12: Pathogen Causing SSI OnPositive Growth (Show the fields from 2-6 if the second option is selected)
Working Fourth Step: Has SSI Been Detected? (Radio Buttons - If selected No, end the session)
@bushramustafa

**Comment by bushramustafa** [comment]
- [ ] Post-op Antibiotic (Drop-box) field is missing @sohail0992

**Comment by bushramustafa** [comment]
@sohail0992 

- [ ] User should be able to view their entries only in the Submitted View
- [ ] Add information icon with Pathogen Classification (where applicable) and add text, "Please select as per the culture report."

**Comment by bushramustafa** [comment]
@sohail0992 

- [ ] In step 5, field Surgical Procedure Planning, remove brackets from its three fields.
- [ ] In step 8, update the (under sterile conditions) to (Under Sterile Conditions)
- [ ] In Step 11, when I select No, the field Number of Times Post-op Antibitoc Changed should not appear.
- [ ] In Step 11, change Numbers of Times Post-op Antibitoc Changed to Number of Times Post-op Antibitoc Changed
- [ ] In step 3, field SSI Criteria, add 'Other evidence of infection found on invasive procedure, gross anatomic exam, or histopathologic exam' and 'Other Signs & Symptoms' to the cascaded checkboxes of the Signs & Symptoms'
- [ ] In Step 6, Other Comorbid Condition text box should only show if Others is selected in the Comorbid Condition.
- [ ] In Step 11, update the bullet point of the field Indication for Post-op Antibiotic from 'Treating Suspected or Non-infection' to 'Treating Suspected or Known Infection'.
