### ISSUE TITLE
SSI form Checklist

### ISSUE THREAD

**Issue by mubassirhayat** [codeforpakistan/HCAIs-Surveillance-App#19]
- [x] Order of fields to follow what dr. Naseem shared in the [doc here](https://docs.google.com/document/d/1Vpf5t5kgJB2NpyzEBTZws6dgoEx7Kxed76elH9-HzGU/edit#heading=h.h9rfhax21wtm)
- [x] Change PCR to PCN in the form fields JSON
- [x] All date fields will have a calendar
- [x] Guardian CNIC & contact number (New fields to be added to the JSON of SSI Form)
- [x] Calculate age from dob (New field type that calculates age)
- [x] Same experience as the web app she showed [here](http://admin.inicc.org/admin/)
- [x] ICD-10-PCS Coding full list not added. Only shows the first 20
- [x] The list for the Event type field has changed, need to make changes accordingly in the SSI form JSON. Options are Superficial Incision, Deep Incision, Organ/Space
- [x] Add and use weight and height fields to calculate BMI 
- [x] Add death boolean field
- [x] Based on BMI please determine overweight, obese, etc. 
- [x] remove “negative culture” from the SSI Form
- [x] Where we have yes/no we add the "unknown" option as well
- [x] Get complete lists for all the dropdowns from the focal person.
- [x] Tally the JSON fields with [SSI Module Form Fields doc](https://docs.google.com/document/d/1Vpf5t5kgJB2NpyzEBTZws6dgoEx7Kxed76elH9-HzGU/edit?usp=sharing)
